version: '3'
services:
  snapify-app:
    build:
      context: .
      args:
        - MONGODB_URI
        - NEXTAUTH_URL
        - NEXTAUTH_SECRET
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
